version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: sxmething/foodgram_backend
    depends_on:
      - db
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
  frontend:
    env_file: .env
    image: sxmething/foodgram_frontend
    command: cp -r /app/build/. /app/static/
    volumes:
      - static:/app/static/
  gateway:
    depends_on:
      - backend
    image: sxmething/foodgram_gateway
    env_file: .env
    ports:
      - 8090:80
    volumes:
      - static:/app/static/
      - media:/app/media/